---
- name: Update package database
  become: yes
  become_user: root
  pacman:
    update_cache: yes

- name: Install official packages
  become: yes
  become_user: root
  pacman:
    name:
      # System utilities
      - htop
      - brightnessctl
      - git

      # Audio stack
      - pipewire
      - pipewire-pulse
      - pipewire-alsa
      - pipewire-jack
      - pavucontrol
      - pulsemixer

      # Applications
      - firefox
      - neovim
      - libreoffice-fresh
      - foot
      - foot-terminfo
      - thunar

      # Bluetooth
      - blueman
      - bluez

      # Wayland/Hyprland
      - hyprland
      - wofi
      - waybar
      - hyprpaper

      # Theming
      - nwg-look

      # Shell & Shenanigans
      - ttf-jetbrains-mono
      - zsh
      - zsh-completions
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - zsh-vi-mode
      - starship
      - fzf
      - ripgrep
      - fd
      - bat
      - eza
      - zoxide
      - tmux
      - lazygit
      - jq
      - yq

    state: present

- name: Install AUR packages
  kewlfft.aur.aur:
    name:
      - pacman-contrib  # for 'checkupdates'
      - visual-studio-code-bin
      - spotify
      - obsidian
      - nerd-fonts
      - pywal
      - python-pywalfox
      - hyprpicker
      - otf-codenewroman-nerd
      - noto-fonts-emoji
      - swaync
      - hypridle
      - hyprlock
      - qogir-icon-theme
      - materia-dark
      - hyprshot
      - pyprland
      - cliphist
    use: "{{ aur_helper }}"
    state: present

- name: Enable bluetooth service
  become: yes
  become_user: root
  systemd:
    name: bluetooth
    enabled: yes
    state: started

- name: Check current shell
  command: echo $SHELL
  register: current_shell
  changed_when: false

- name: Change default shell to zsh
  become: yes
  become_user: root
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  when: current_shell.stdout != "/usr/bin/zsh"

# TODO: hyprland needs to be running to use hyprpm.
#- name: Add hypr-dynamic-cursors plugin
  #command: hyprpm add https://github.com/virtcode/hypr-dynamic-cursors
  #register: hyprpm_add
  #changed_when: "'Already installed' not in hyprpm_add.stdout"
  #failed_when: 
    #- hyprpm_add.rc != 0
    #- "'Already installed' not in hyprpm_add.stdout"
#
#- name: Enable dynamic-cursors plugin
  #command: hyprpm enable dynamic-cursors
  #register: hyprpm_enable
  #changed_when: "'Already enabled' not in hyprpm_enable.stdout"
  #failed_when:
    #- hyprpm_enable.rc != 0
    #- "'Already enabled' not in hyprpm_enable.stdout"

- name: Check if .config exists and is not a symlink
  stat:
    path: "{{ config_path }}"
  register: config_stat

- name: Backup existing .config if it exists and is not a symlink
  command: mv "{{ config_path }}" "{{ config_path }}.backup.{{ ansible_date_time.epoch }}"
  when: 
    - config_stat.stat.exists
    - not config_stat.stat.islnk

- name: Remove existing .config symlink if it points to wrong location
  file:
    path: "{{ config_path }}"
    state: absent
  when:
    - config_stat.stat.exists
    - config_stat.stat.islnk
    - config_stat.stat.lnk_source != config_source_path

- name: Create symlink for .config directory
  file:
    src: "{{ config_source_path }}"
    dest: "{{ config_path }}"
    state: link
    force: no

