---
- name: Update package database
  become: yes
  become_user: root
  pacman:
    update_cache: yes

- name: Install official packages
  become: yes
  become_user: root
  pacman:
    name:
      # System utilities
      - htop
      - brightnessctl
      - git

      # Audio stack
      - pipewire
      - pipewire-pulse
      - pipewire-alsa
      - pipewire-jack
      - pavucontrol
      - pulsemixer

      # Applications
      - firefox
      - neovim
      - libreoffice-fresh
      - kitty
      - thunar

      # Bluetooth
      - blueman
      - bluez

      # Wayland/Hyprland
      - hyprland
      - wofi
      - waybar

      # Theming
      - nwg-look

      # Shell & Shenanigans
      - zsh
      - zsh-completions
      - starship
      - fzf
      - ripgrep
      - fd
      - bat
      - eza
      - zoxide
      - tmux
      - lazygit
      - neofetch
      - tree
      - jq
      - yq

      # System optimization
      - cpupower
      - thermald
      - powertop
      - irqbalance
      - preload

    state: present

- name: Install AUR packages
  kewlfft.aur.aur:
    name:
      - visual-studio-code-bin
      - spotify
      - obsidian
      - nerd-fonts
      - pywal
      - hyprpicker
      - otf-codenewroman-nerd
      - swaync
      - hypridle
      - hyprlock
      - qogir-icon-theme
      - materia-dark
      - hyprshot
      - pyprland
    use: "{{ aur_helper }}"
    state: present

- name: Enable bluetooth service
  become: yes
  become_user: root
  systemd:
    name: bluetooth
    enabled: yes
    state: started

- name: Check current shell
  command: echo $SHELL
  register: current_shell
  changed_when: false

- name: Change default shell to zsh
  become: yes
  become_user: root
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  when: current_shell.stdout != "/usr/bin/zsh"

- name: Add hypr-dynamic-cursors plugin
  command: hyprpm add https://github.com/virtcode/hypr-dynamic-cursors
  register: hyprpm_add
  changed_when: "'Already installed' not in hyprpm_add.stdout"
  failed_when: 
    - hyprpm_add.rc != 0
    - "'Already installed' not in hyprpm_add.stdout"

- name: Enable dynamic-cursors plugin
  command: hyprpm enable dynamic-cursors
  register: hyprpm_enable
  changed_when: "'Already enabled' not in hyprpm_enable.stdout"
  failed_when:
    - hyprpm_enable.rc != 0
    - "'Already enabled' not in hyprpm_enable.stdout"

