---
- name: Install dependencies
  pacman:
    name:
      - reflector
      - cpupower
      - thermald
      - irqbalance
      - cpuower
      - preload

- name: Enable performance services
  become: yes
  become_user: root
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - thermald
    - irqbalance
    - fstrim.timer
    - cpupower
    - preload

- name: Configure reflector for mirror updates
  become: yes
  become_user: root
  copy:
    content: |
      --save /etc/pacman.d/mirrorlist
      --protocol https
      --country "US,CA"
      --latest 10
      --sort rate
    dest: /etc/xdg/reflector/reflector.conf
    backup: yes

- name: Enable reflector timer
  become: yes
  become_user: root
  systemd:
    name: reflector.timer
    enabled: yes
    state: started

- name: Set CPU governor to performance
  become: yes
  become_user: root
  lineinfile:
    path: /etc/default/cpupower
    regexp: '^governor='
    line: "governor='ondemand'"
    create: yes
  notify: restart cpupower

- name: Configure swappiness
  become: yes
  become_user: root
  sysctl:
    name: vm.swappiness
    value: '10'
    state: present
    sysctl_file: /etc/sysctl.d/99-swappiness.conf

- name: Configure additional sysctl parameters
  become: yes
  become_user: root
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/99-desktop-optimization.conf
  loop:
    - { name: 'vm.vfs_cache_pressure', value: '50' }
    - { name: 'vm.dirty_ratio', value: '10' }
    - { name: 'vm.dirty_background_ratio', value: '5' }

