theme = "catppuccin_frappe"

# ----- Editor

[editor]
line-number = "relative"
bufferline = "multiple"
scrolloff = 15

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"
prefix-len = 2

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.statusline]
left = ["file-name", "file-modification-indicator", "file-type", "read-only-indicator"]
center = ["diagnostics", "spinner"]
right = ["version-control", "spacer", "position", "total-line-numbers"]
separator = "│"

[editor.indent-guides]
render = true
character = "╎"  # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1


# ----- Keys

[keys.normal]
C-s = ":write"
C-q = ":buffer-close"
A-s = "save_selection"  # jumplist save
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-t = ':sh footclient'  # term
S-t = ':sh footclient -D $(dirname %{buffer_name})'  # term in cwd
# Yazi!:
C-e = [
  ':sh rm -f /tmp/helix_yazi_chooser_file_uniq',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/helix_yazi_chooser_file_uniq',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/helix_yazi_chooser_file_uniq}',
  ':redraw',
]
# Go to next search result, adding the current one to selection.
# (instread of entering select mode, going to next search result, and leaving select mode):
C-n = 'extend_search_next' 
# Git blame current line, multiple commits:
C-b = ":sh git log -n 5 --format='format:%%h (%%an: %%ar) %%s' --no-patch -L%{cursor_line},+1:%{buffer_name}"

[keys.insert]
C-s = "normal_mode"  # double tap s for normal mode + save buffer
C-backspace = "delete_word_backward"
C-del = "delete_word_forward"
C-right = "move_next_word_start"
C-left = "move_prev_word_start"

[keys.normal."+"]
a = ":run-shell-command echo test"
d = ":pipe cat"
g = ":insert-output cat poop"
