theme = "catppuccin_frappe"

# ----- Editor

[editor]
line-number = "relative"
bufferline = "multiple"
scrolloff = 15

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"
prefix-len = 2

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.statusline]
left = ["file-name", "file-modification-indicator", "file-type", "read-only-indicator"]
center = ["diagnostics", "spinner"]
right = ["version-control", "spacer", "position", "total-line-numbers"]
separator = "│"

[editor.indent-guides]
render = true
character = "╎"  # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1


# ----- Keys

[keys.normal]
C-s = ":write"
A-s = "save_selection"  # jumplist save
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"

[keys.insert]
C-s = "normal_mode"
C-backspace = "delete_word_backward"
C-del = "delete_word_forward"
C-right = "move_next_word_start"
C-left = "move_prev_word_start"

[keys.normal."+"]
a = ":run-shell-command echo test"
d = ":pipe cat"
